### ISSUE TITLE
Unable to mount ISO/loop devices.

### ISSUE THREAD

**Issue by beanaroo** [coldfix/udiskie#101]
First of all, I'm not sure if this is a bug or if I'm not understanding user-space ISO mounting correctly.

I can use udisks2 to successfully mount an ISO via:

    $ udisksctl loop-setup -r -f image.iso
    $ udisksctl mount -b /dev/loop1p1

Udiskie fails when specifying the ISO with:
```
DEBUG [2016-02-06 15:06:36,772] udiskie.config: IgnoreDevice(match={'is_block': False}, value=True) created
DEBUG [2016-02-06 15:06:36,773] udiskie.config: IgnoreDevice(match={'is_external': False}, value=True) created
DEBUG [2016-02-06 15:06:36,773] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value=True) created
WARNING [2016-02-06 15:06:37,318] udiskie.udisks2: Device not found: /home/bean/Resources/Distros/ubuntu-15.10-server-amd64.iso
ERROR [2016-02-06 15:06:37,318] udiskie.mount: no device found owning "/home/bean/Resources/Distros/ubuntu-15.10-server-amd64.iso"
```
Udiskie fails when specifying the loop device, created by udisksctl, with:
```
DEBUG [2016-02-06 14:46:08,372] udiskie.config: IgnoreDevice(match={'is_block': False}, value=True) created
DEBUG [2016-02-06 14:46:08,372] udiskie.config: IgnoreDevice(match={'is_external': False}, value=True) created
DEBUG [2016-02-06 14:46:08,372] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value=True) created
DEBUG [2016-02-06 14:46:08,582] udiskie.mount: found device owning "/dev/loop1p1": "/org/freedesktop/UDisks2/block_devices/loop1p1"
DEBUG [2016-02-06 14:46:08,639] udiskie.config: IgnoreDevice(match={'is_external': False}, value=True) used for /org/freedesktop/UDisks2/block_devices/loop1p1
WARNING [2016-02-06 14:46:08,639] udiskie.mount: not mounting /org/freedesktop/UDisks2/block_devices/loop1p1: unhandled device
```

I have not created any configuration files.

**Comment by coldfix** [comment]
Hey,

sorry for the delay. Loop devices were not handled by udiskie so far.

I have now added basic support for loop devices. However, you must enable this explicitly in your config file because I'm not sure yet how to handle these devices by default.

```yaml
# ~/.config/udiskie/config.yml
ignore_device:
  - is_loop: true
    ignore: false
```

or

```yaml
ignore_device:
  - loop_file: "/home/bean/Resources/Distros/ubuntu-15.10-server-amd64.iso"
    ignore: false
```

The problem with the first rule is that it also sets udiskie to handle system loop devices which is undesired. I don't see any straightforward way to distinguish user-made loop devices from system devices, both are reported as system internal. There is the `SetupByUID` property but this one is unavailable in udisks1 - maybe I'll just add this property for udisks2 and leave it blank on the udisks1 backend.

The second rule has the downside that each device must be configured individually - currently there is no pattern matching (e.g. enable all *.iso files) from the config rules, although I'm considering to change that at some point.

**Comment by coldfix** [comment]
I should further add, that udiskie can not yet be used to directly mount `.iso` files that were not previously setup as loop devices. This seems to be possible only with udisks2 not with udisks1.

Probably, I should just add this for the udisks2 backend. What do you think?

**Comment by philer** [comment]
> Probably, I should just add this for the udisks2 backend. What do you think?

I vote yes, could definitely use that. Right now I'm using a hacky bash script with udisksctl because querying d-bus from shell is a pain.

**Comment by coldfix** [comment]
@beanaroo @philer I have implemented this feature and but I'd like your opinion on the UI before merging it to master.

Should udiskie hide the fact that there is a loop device behind mounted ISO images?

I.e., should there be separate options to unmount/delete the loop device or just one unmount that does both jobs. Should udiskie allow setting up loop devices without also mounting them?

My preliminary opinion is that udiskie should hide the fact that there is a loop device. The majority of users will probably only be confused by having additional options, and there is always `udisksctl` to get more fine-grained control.

**Comment by philer** [comment]
I think consistency should be the primary concern. A loop device is similar to a LUKS container in that you have to take one extra step before you can mount the actual file system:
 1. Step: Unlock LUKS container <-> Setup loop device
 2. Step: Mount the file system from the mapped device

In the case of LUKS containers you opted for a `-r` and `--force` switch on the command line for recursive (un)mounting and separate steps in the tray menu (assuming `--no-automount`). So I think you should do the same for loop devices because it would be confusing if one type behaves differently than another.

That said I'd actually still prefer it if the tray menu would do recursive (un)mounting in all cases, different from what it is currently doing.
Especially since there may be LUKS containers inside image files, which requires three three separate steps to a full (un)mount (this is actually what I'm doing, not just a hypothetical). In that case the `-r`/`--force` options should make sure to perform the full recursive (un)mount.

**Comment by coldfix** [comment]
Okay, I'll likely complete this feature this weekend.

The tray menu should *already* do recursive unmounts/locks/detaches. Under which circumstances do you experience problems with this? Does it work using the `udiskie-umount -f` tool? Can you open a separate issue with the corresponding description.

Regarding recursive mounts/unlocks. I disagree that this should be done by default if you have automounting disabled: It might be that there are several partitions in one container and if the user disables auto-mounting, she should still have control which partitions to mount, which not to. I could, however, imagine a separate menu item `Recursive unlock` or similar, or alternatively allow to configure udiskie to do this.

**Comment by coldfix** [comment]
Added handling for loop devices. For convenience, the container will be managed same as the loop file by default: 

- `udiskie-mount image.iso` also mounts the loop device unless using the `-R` (`--no-recursive`) option
- `udiskie-umount image.iso` also detaches the loop device unless using the `-D` (`--no-detach`) option
