### ISSUE TITLE
Is it possible to use as a library instead of CLI?

### ISSUE THREAD

**Issue by mbusb** [coldfix/udiskie#108]
Is it possible to use your package as a library instead of simply executing from terminal? If yes then where is the documentation for this?

**Comment by coldfix** [comment]
Please refer to my previous answer to your question in #86 as well as my answer on [this question](https://github.com/coldfix/udiskie/issues/100#issuecomment-174665144).

**Comment by mbusb** [comment]
Well, getting udisk up and running is complicated. That is why I have posted this question. I am sure that you have already implemented this feature (simply calling some function with usb path as argument) in udiskie. What I am expecting from your program is something like this:-

```
from udiskie import mount
mount ('/dev/sdb1')
```

This way you are expanding your package to (seasonal) developers as well.

**Comment by mbusb** [comment]
I forgot that I have asked similar question to you some time back. Sorry for double posting.

**Comment by coldfix** [comment]
> Well, getting udisk up and running is complicated

It's not that complicated. The [rather short snippet](https://github.com/coldfix/udiskie/issues/100#issuecomment-174744989) I referred to should get your `/dev/sdb1` to successfully mount and unmount. The same thing can be done even more concisely using the PyGI Udisks2 binding. Also note that the answer mentions additional documentation which will be helpful in clarifying further questions.

> Is it possible to use your package as a library instead of simply executing from terminal? If yes then where is the documentation for this?

At this point, I don't recommend using udiskie as library since I switched to a custom async implementation which will be inconvenient to code for in small projects that are fine using a synchronous approach.

> This way you are expanding your package to (seasonal) developers as well.

I strongly recommend using the udisks API directly. This brings with it much less *luggage* than udiskie and is more stable. I don't keep any promises to keep the internal udiskie API intact (in fact, I have a yearning desire to rework this unholy mess).

**Comment by mbusb** [comment]
Thanks for the fast reply. You may want to include this (not recommending the use of udiskie as library) somewhere in your wiki/ documentation to avoid similar questions in future. Closing this issue.

**Comment by coldfix** [comment]
> You may want to include this (not recommending the use of udiskie as library) somewhere in your wiki/ documentation

I probably should, but I'm really swamped with work in the next few weeks.

Just to clarify: I'd prefer as well to have udiskie being usable as a lean and clean wrapper library over the low level udisks dbus API (as was my intention a few years ago), but for now this goal has become difficult with the adoption of the custom async layer for now.
