### ISSUE TITLE
Udiskie-mount and udiskie-umount send 

### ISSUE THREAD

**Issue by fmitha** [coldfix/udiskie#112]
It looks like `udiskie-mount` and `udiskie-umount` direct their output on mount and unmount to standard
error. I'm unable to think of a reason for this.
```
udiskie-mount -a > /dev/null
mounted /org/freedesktop/UDisks2/block_devices/sde1 on /media/faheem/My Passport
```
Similarly
```
udiskie-umount -a > /dev/null
unmounted /org/freedesktop/UDisks2/block_devices/sde1
```

**Comment by coldfix** [comment]
Hey, thanks for your report. I'll have a look next week.

**Comment by coldfix** [comment]
Hey, you can just use `udiskie-mount -q` to get rid of the info-level messages. Is there any further necessity to have the info messages report to stdout? It could be done, but I don't like the tradeoffs right now.

**Comment by fmitha** [comment]
Yes, I could use `-q`. But what is the reason why the info messages report to standard out?

Regards, Faheem Mitha

**Comment by coldfix** [comment]
It's a technical reason. I'm using the `logging` module to control which messages and that module turns out to log everything to stderr by default independently of the log level. With some hacking it's possible to add handlers for specific log levels that log to stdout, but I don't really like the necessary effort atm.

**Comment by fmitha** [comment]
Hi Thomas,

Ok. If you don't want to change that, close the issue, or keep it open, whatever you want.
