### ISSUE TITLE
Flatten systray menu

### ISSUE THREAD

**Issue by philer** [coldfix/udiskie#119]
Hi there, lovely tool!

I realize this is more of a personal preferences but I don't really like navigating through nested menus by hovering with a cursor. It's tedious. I rarely have more than 2, maybe 3 usb devices connected that need to be managed by udiskie so I'd find it a lot easier if the menu was flat.

Edit: Also it would be quite helpful if there was a way to get the equivalent of `udiskie-umount --force` behind a systray menu entry. Maybe just put a confirmation dialog behind the Eject button that will ask something along the lines of "One or more partitions on this device are still mounted (list of folders). Do you want to unmount them all? Cancel/Continue"

**Comment by coldfix** [comment]
Hey,

regarding menus: you want a fully flat menu with no submenus at all? I could add a configuration option to select this behaviour.

regarding the other issue, the menu items already imply ``--force``. Do you suggest showing a dialog, or did you have problems where it did not work? (it will never work if the device is in use)

**Comment by philer** [comment]
Yeah, an option for a completely flat menu would be perfect. The menu entries should still be sorted (alphabetical sorting by device would be ideal).

As for my other issue it appears to be related to LUKS. I have a USB flash drive (`/dev/sdc`) with one LUKS encrypted partition (`/dev/sdc2`) on it and another one that is not encrypted (`/dev/sdc1`) although I don't think that second one matters. I'm running udiskie version 1.4.12 with the `--no-automount` switch.

Via command line I can `udiskie-mount -r /dev/sdc2` which unlocks and mounts the encrypted partition. I can then `udiskie-umount --force --detach /dev/sdc` and everything is unmounted and locked as expected.

However if I do the equivalent via the systray menu it seems to omit the recursive options. Clicking on "Unlock *uuid-of-sdc2*" only unlocks it but doesn't mount. Regardless of whether I then manually mount the partition or not, a subsequent "Eject /dev/sdc" or "Unpower /dev/sdc" does nothing, except spit out the following error on the command line where I'm running the daemon:
```
failed to eject /org/freedesktop/UDisks2/block_devices/sdc: GDBus.Error:org.freedesktop.UDisks2.Error.DeviceBusy: Cannot eject drive in use: Encrypted device /dev/sdc2 is unlocked
```

**Comment by coldfix** [comment]
Okay.

First, the tray menu icon does not mount recursively by design, since most of the time you would have `--automount` enabled. I don't really like to add a dialog or similar to ask the user here, but will think about adding better configuration options.

Second: that seems strange. Can you provide the output of `udisksctl info -b /dev/sdc` for all involved devices?

Third: please provide output of `udisksctl info`. Does the device disappear if you select "Unpower" or does it stay? If it does disappear, I'd say udiskie shows a working option, so this is the best that can be done as default. However, you can configure udiskie to ignore that device, see the man page.

**Comment by philer** [comment]
Sure. This will be long so I'm throwing it in a pastbin (I don't think there's anything security sensitive in there but I'm still setting a paste expiration of 2 weeks).

I'm still using `--no-automount`. I like having multiple partitions on external devices but I don't always want all of them mounted (for example a backup partition should only be accessible when it's actually needed).

1. [`/dev/sdc(|1|2)` Freshly plugged in, nothing mounted](http://pastebin.com/4RjmU4tt)
2. [`/dev/dm-0` after unlocking `/dev/sdc2` via systray menu](http://pastebin.com/BrBL02uD)
3. [`/dev/sdb` (card reader) before doing anything](http://pastebin.com/51AgagPt)
4. `/dev/sdb` disappears completely after Unpowering via systray menu:
```
$ udisksctl info -b /dev/sdb
Error looking up object for device /dev/sdb
```
I don't have a card with me right now so I can't test whether it'll re-activate the device when I insert something. I can do that later when I get home. I *am* using the card reader occasionally, so I don't want to just turn it off on startup if there is no way to wake it up again.

**Comment by coldfix** [comment]
- what exactly doesn't work now? please provide a precise description what you are doing, and provide the output of udiskie in verbose mode (`udiskie -v`)
- you should be able to add an unignore-rule for `/dev/sdb?` (with a question-mark as wildcard in the end) in order to unignore the cards

btw: It would be better to open separate threads for each issue, to make it easier to follow/focus, we have 3 issues in this thread now with a patchwork of information;)

also: better to copy paste in here - not to a pastebin - so people can later evaluate if they had the same problem.

**Comment by coldfix** [comment]
I've created a flat menu that can be requested via the `-m flat` command line option or via the config file. Any opinions on ordering of actions?

rather something like:

```
Mount /dev/sdb
Unmount /dev/sdc
---
Eject /dev/sdb
Eject /dev/sdc
---
Unpower /dev/sdb
Unpower /dev/sdc
```

or


```
Mount /dev/sdb
Eject /dev/sdb
Unpower /dev/sdb
---
Unmount /dev/sdc
Eject /dev/sdc
Unpower /dev/sdc
```

**Comment by coldfix** [comment]
Hey,

there is now a flat menu as requested. I think I like this behaviour more than the old menu, so it might become the default in a future version.

For now the new behaviour can be requested with `udiskie -m flat` or by putting

```yaml
program_options:
  menu: flat
```

in the config file. I hope this meets your expectations. Otherwise: suggestions are always welcome.

Best regards,
Thomas

**Comment by coldfix** [comment]
@philer 
Btw., regarding your SD card reader, have you tried a rule like

```
ignore_device:
  - device_file: /dev/sdb
    has_media: False
    ignore: True
```

which is supposed to ignore the device only if there is no media (not sure if `has_media` will work correctly, though)

**Comment by philer** [comment]
I love the menu, this is exactly what I was hoping for. Danke! ;D
Only issue for me right now is that the icons aren't working but that might have to do with the way I installed it (I have never used Python's setuptools before and was previously using the pip version).

The SD card reader ignore rule you suggested appears to work fine. The tray icon remains hidden until a card is plugged in and disappears again after ejecting/unplugging the card. A small concern is that the menu still shows the 'Unpower' button, which will cause the entire card reader to disappear until the next reboot. Of course I can just remember not to press it but I'm guessing this might be confusing for others who have a similar built-in device (could this also apply to CD/DVD drives?).

**Comment by coldfix** [comment]
[Icons](https://github.com/coldfix/udiskie/wiki/Installation#gtk-icons) not working is a result of user installation. If you want to make the icons work, you have have to use the root installation or install them separately into the system folder:

```
cp ./icons/scalable /usr/share/icons/hicolor -r
gtk-update-icon-cache /usr/share/icons/hicolor
```

**Comment by coldfix** [comment]
I might add the possibility to hide individual actions on a per-device basis (#124) at some time, but this is not really a priority for me right now.
