### ISSUE TITLE
Ways to query udiskie for information

### ISSUE THREAD

**Issue by philer** [coldfix/udiskie#122]
I'm trying to automate some stuff right now (basically mount a specific LUKS partition as part of a bigger process) which requires me to figure out the current device ID of a partition. While this is almost trivial as root (parsing the output of tools like `blkid` or `lsblk`) it's a lot more tedious to do as a regular user.
I'm not even sure yet what the best way of implementing it will be. All I really need is a list of devices managed via udiskie/udisks2 (typically those not managed by `/etc/fstab`) with device file, file system, uuid, label, mount point (if any) and maybe size. So far I've been trying to build a bash script but the output of `udisksctl` is quite annoying to parse and working with dbus from bash is just plain masochism. You'd think that info is easy to get but alas… 

So I could think of two ways to make this work in conjunction with udiskie:

1. A cli tool like `udiskie-info` could be used to access information in simple readable format. For example 
  * `udiskie-info` could output a simple list of block devices mounted/mountable via udisks
  * `udiskie-info --blkid` could output information in the typical `blkid` formatting. (In case anyone is wondering, native `blkid` doesn't return reliable information when run as non-root.)
  * The output formatting options of `lsblk` could also serve as inspiration.
2. If udiskie were to provide a (documented) Python API people could use that in a simple Python script and call it where needed. I'd really like that, actually.

Let me know what you think. If you know a better way of doing what I'm trying to do I'll be happy as well.

**Comment by coldfix** [comment]
Hey.

> 1. A cli tool like `udiskie-info` could be used to access information in simple readable format. For example

I'm not opposed to this, but I currently lack time to think through what information should be made available, what command line options to provide, etc. If you provide a "usage information" string (like in udiskie.cli.Daemon etc), I wouldn't be opposed to implement it and later on add options if needed.

But maybe it's better for you to use a python API, regarding option 2:

> 2. If udiskie were to provide a (documented) Python API people could use that in a simple Python script and call it where needed. I'd really like that, actually.

That's currently not really an option due to the async layer with which udiskie is coded, there is no convenient API for outside use.

However, udiskie is just a client program for *UDisks* which is the backend daemon that provides a well-documented DBus API. Does #86 as well as my answer on [this question](https://github.com/coldfix/udiskie/issues/100#issuecomment-174665144) help - or is the overhead too much for your use case?

**Comment by coldfix** [comment]
I'm sorry, I don't know any non-root equivalents except for `udisksctl`. There is also [storaged](https://github.com/storaged-project/storaged), which I have never used but it may include some of the things that you are looking for - not sure.

I'm open to improve the udiskie UI to allow some of the things you wish to do using command line tools.

**Comment by coldfix** [comment]
Hey,

I've added a very basic `udiskie-info`. However, my main concern was a use-case of my own, so it may not address all your needs. Let me know if you'd like something changed/added or otherwise feel free to close the issue.

(Note that the exact command line interface may still change. This is also the reason that I will not add "official" documentation for this utility yet")

Usage examples:

```
# list all managed devices:
$ udiskie-info -a
/dev/mapper/luks-7354dbf1-a8ee-4d70-bfcd-4e7d7ccc9af6
/dev/sdb
/dev/sdb1
/dev/sdb2
/dev/sdc
/dev/sdc1
/dev/sdd
/dev/sdd1
/dev/sr0

# list only luks devices
$ udiskie-info -a -f is_luks
/dev/sdb2

# list only filesystems that are not already mounted:
$ udiskie-info -a -f is_filesystem -f '!is_mounted'
/dev/mapper/luks-7354dbf1-a8ee-4d70-bfcd-4e7d7ccc9af6
/dev/sdb1
/dev/sdc1
/dev/sdd1
...

# get partition labels for specific devices
$ udiskie-info -o id_label /dev/sdb1 /dev/sdc1
MAD
STÏCKŸé
```

At this time, you can only have one output column, but several filters.

**Comment by philer** [comment]
That's sounds perfect, actually. I'll check it out when I got some more time.
Thanks for adding this feature!

**Comment by coldfix** [comment]
@philer FYI, I have modified the `udiskie-info` utility to allow specifying a format string such as:

```
udiskie-info -a -o "{device_presentation}:{is_luks}:{ui_label}"
```

It has access to the valid attributes.
Furthermore, startup time for the utility will slightly decrease in the next release (hopefully).

**Comment by philer** [comment]
That's really cool, thanks for adding!

(btw it didn't quite work when you mentioned it but now it does.)
