### ISSUE TITLE
Mount NTFS drive: operation not permitted

### ISSUE THREAD

**Issue by NullInfinity** [coldfix/udiskie#131]
When trying to mount a removable NTFS hard drive with `udiskie-mount`,
```sh
udiskie-mount /dev/sdf1
```
I receive the following error message
```sh
failed to mount /org/freedesktop/UDisks2/block_devices/sdf1 GDBus.Error:org.freedesktop.UDisks2.Error.OptionNotPermitted: Requested filesystem type `ntfs-3g' is neither well-known nor in /proc/filesystems nor in /etc/filesystems
```

I receive this error when running as regular user or as root. I have `ntfs-3g` installed and running `ntfs-3g /dev/sdf1` as root successfully mounts the drive.

**Comment by coldfix** [comment]
Hey,

thanks for taking the time to report the issue.

Are you using udisks2 or udisks1?

Also, does any of the following two commands work:

```
udisksctl mount --block-device /dev/sdf1
udisksctl mount --block-device /dev/sdf1 --filesystem-type ntfs-3g
udisksctl mount --block-device /dev/sdf1 --filesystem-type ntfs
```

If not, the issue is probably not in udiskie, but with permissions or system configuration.

If the first of the above three commands worked, in `udiskie/mount.py` line 206 can you change the line that reads

```diff
-        kwargs = dict(fstype=fstype, options=options)
+        kwargs = dict(options=options)
```

Also, start udiskie  with `-v` to see what options are passed at the point?

It may also be related to polkit permissions. Did you follow the instructions at https://github.com/coldfix/udiskie/wiki/Permissions?

Best, Thomas

**Comment by NullInfinity** [comment]
I am using `udisks2`.

Your first and third `udisksctl` commands successfully mounted the drive. The second one, with `--filesystem-type ntfs-3g` failed with a similar error to the one output by `udiskie`.

Making the change you suggested above to `udiskie/mount.py` solved the problem. However, I also came upon this [Gentoo forums thread](https://forums.gentoo.org/viewtopic-p-6671453.html) with a similar error. A solution suggested there was to add `ntfs-3g` to `/etc/filesystems` (which I suppose makes it "known"). That fixed the problem too.

I'm not an expert on this so I don't know which solution is the correct one, i.e. either patching `udiskie` or just updating `/etc/filesystem`. Let me know what you think.

**Comment by coldfix** [comment]
I will update udiskie to make it easier. In fact, I did not see any reason to explicitly specify the filesystem type so far (this was already in the code when I adopted the package).
