### ISSUE TITLE
gnome-keyring might be a dependency

### ISSUE THREAD

**Issue by bluehood** [coldfix/udiskie#152]
Hello, I installed udiskie via pacman. Worked out of the box when I fired it up, and I love the simplicity of the program.

After I while though, udiskie crashes due to the absence of a provider of the  on my arch installation.

```
Dec 04 00:54:06 meeseeks gpg-agent[29086]: gpg-agent (GnuPG) 2.2.3 starting in supervised mode.
Dec 04 00:54:06 meeseeks gpg-agent[29086]: using fd 3 for extra socket (/run/user/1000/gnupg/S.gpg-agent.extra)
Dec 04 00:54:06 meeseeks gpg-agent[29086]: using fd 4 for std socket (/run/user/1000/gnupg/S.gpg-agent)
Dec 04 00:54:06 meeseeks gpg-agent[29086]: using fd 5 for browser socket (/run/user/1000/gnupg/S.gpg-agent.browser)
Dec 04 00:54:06 meeseeks gpg-agent[29086]: using fd 6 for ssh socket (/run/user/1000/gnupg/S.gpg-agent.ssh)
Dec 04 00:54:06 meeseeks gpg-agent[29086]: listening on: std=4 extra=3 browser=5 ssh=6
Dec 04 00:54:06 meeseeks pinentry[29088]: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Dec 04 00:54:06 meeseeks gpg-agent[29086]: Failed to lookup password for key ... with secret service: The name org.freedesktop.secrets was not provided by any .service files
Dec 04 00:55:31 meeseeks systemd-coredump[29716]: Process 21974 (udiskie) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 21974:
                                                  #0  0x00007f39b13e7cd2 n/a (libglib-2.0.so.0)
                                                  #1  0x00007f39b13ed421 g_log_writer_default (libglib-2.0.so.0)
                                                  #2  0x00007f39b13e7d72 g_log_structured_array (libglib-2.0.so.0)
                                                  #3  0x00007f39b13e815a g_log_structured (libglib-2.0.so.0)
                                                 ....
````

So my understanding is that at some intervals `udiskie` calls into the `org.freedesktop.secrets` service via `libglib` but the service is not there so `udiskie` crashes.
I think installing `gnome-keyring`, which provides `org.freedesktop.secrets`, should fix this, but `gnome-keyring` is not listed as a dependency of the project (at least on arch linux). Will report back soon.

**Comment by coldfix** [comment]
Hey, thanks for taking the time to report the issue!

Does this happen due to some specific event? There is no explicit use of `gnome-keyring` in udiskie, so I wonder how this occurs. The only places, where I could imagine this happening is if some dbus action requires authentication. However, personally, I don't have `gnome-keyring` (nor lib) installed right now and haven't encountered this problem so far.

Since the log record for udiskie crash is more than a second later than the gpg stuff, it looks to me that these might be unrelated and udiskie is crashing for some other reason. (Honestly, a crash like this is definitely a bug in glib/pygi, which might of course be triggered due to incorrect usage in udiskie.) 

Can you run udiskie with `-v` to get some hints when this happens approximately?

**Comment by bluehood** [comment]
My conclusions might indeed be wrong -- but I don't see the crash anymore.
Note that it does not _have_ to be `gnome-keyring` as long as someone provides `org.freedesktop.secrets` (the crash happens right after that service is not found).

I will add more information here if I see problems again.

**Comment by coldfix** [comment]
I'll close for now, please reopen if it shows up again.

For reference, was this recorded while running both from xinitrc or similar autostart? Did you encounter the problem once or multiple times? Did it happen after any special event (e.g. clicking menu, or inserting device, unlocking/locking device, etc)?

I would still guess the udiskie crash was probably not related to `org.freedesktop.secrets` missing: The message says "gpg-agent"; shows a different process number and was more than a second before the crash.

If I had to guess, I'd say this was either a bug somewhere in glib itself, or caused by destroying a C object before the python is done with (which can happen e.g. if the python object is kept alive by a weak reference. This happens with some of the pygi callbacks that do not keep proper references to the python objects and thus do not ensure that when the callback happens, the object is still valid.)

Best, Thomas
