### ISSUE TITLE
Long delay between detection/mount / maybe because no notification-daemon can be found?

### ISSUE THREAD

**Issue by aurelg** [coldfix/udiskie#163]
I'm a happy user of `udiskie` on Arch/i3wm since a few years. It always worked well, except that there was a significant delay (typically 30s-1min) between USB mass storage detection and mounting.

For [some unrelated reason](https://github.com/signalapp/Signal-Desktop/issues/2567), I recently had to install a notification daemon ([Dunst](https://github.com/dunst-project/dunst)). Now, `udiskie` is able to mount partitions right after the USB storage is plugged. I wonder if it's related?

**Comment by coldfix** [comment]
Hi, sounds weird to me, but in theory it could be possible that libnotify blocks searching for a notification daemon if there is none.. not sure. It could also be due to an udisks update or even just luck with different hardware or something.

Can you temporarily uninstall dunst and retry or will this mess up your system? If you do uninstall and the issue reappears, try passing the `--no-notify` option to udiskie to make sure.

Anyway, if it is related to notifications, I believe there is no way to fix this in udiskie other than letting the user pass `--no-notify`.

**Comment by aurelg** [comment]
Hi, thanks for your quick reply!

I've been able to confirm that adding/removing Dunst solves/creates the mounting delay. Turning off `udiskie` notifications with `--no-notify` allows for instant mounting even if Dunst is not installed. Might it be worth a sentence in the documentation, like "If you experiment a delay between block device detection and mounting, try to turn off notifications with `--no-notify`"?

Thanks for your help/suggestion :)

**Comment by coldfix** [comment]
I've added a comment to the wiki pages and might transfer this to more proper documentation sometime in the future.
