### ISSUE TITLE
Mount an exfat drive with noexec

### ISSUE THREAD

**Issue by last5bits** [coldfix/udiskie#184]
This is the output of `mount` after running `udiskie-mount -a` with my exfat flash drive:

```
/dev/sdb1 on /run/media/alex/4A45-3453 type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
```

How do I add `noexec` to the list of options? I tried the following to no avail:

```
device_config:
- id_type: fuseblk
  options: [noexec]
```

**Comment by srd424** [comment]
I've just been tearing my hair out with a similar problem with the ntfs driver .. I don't know if exfat is the same, but the ntfs driver only shows generic fuse options in `mount(8)` / `/etc/mtab` - you have to look in the syslog to see what was passed in on the command line. Very annoying!

**Comment by coldfix** [comment]
Hi, your config file looks correct. However, udisks does not let users specify all options on all filesystems, which could be a reason for `noexec` being ignored.

You can run udiskie-mount with `-v` to see which flags udiskie does actually pass on. Everything beyond that point is up to udisks and drivers.

I will close this for now, since this is very old (my apologies:( for not responding earlier). If you're still using udiskie and experiencing this issue with the most recent version, and `udiskie-mount -v [...]` does not show a line like the following, please give me a note and I will reopen and investigate further (more timely I promise):

```
DEBUG [....] udiskie.mount: mounting /org/freedesktop/UDisks2/block_devices/sdb1 with {'options': ['noexec']}
```
