### ISSUE TITLE
Luks encrypted + keyfiles not mounted on first launch

### ISSUE THREAD

**Issue by sheoak** [coldfix/udiskie#191]
I need to re-launch udiskie to mount my luks encrypted usb sticks:

```
cat ~/.dotfiles-private/udiskie/config.yml 

device_config:
- id_uuid: _hidden_
  keyfile: ~/system/keyfile1.key

- id_uuid: _hidden_
  keyfile: ~/system/keyfile2.key
```

```
$ udiskie --version
udiskie 2.0.1
# running first time, nothing is mounted, no error
$ udiskie -T -v -c ${DOTFILES_PRIVATE}/udiskie/config.yml
# second try, error:
$ udiskie -T -v -c ${DOTFILES_PRIVATE}/udiskie/config.yml
DEBUG [2019-12-28 19:37:26,367] udiskie.mount: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/udiskie/mount.py", line 248, in _unlock_from_cache
    password = self._cache[device]
  File "/usr/lib/python3.8/site-packages/udiskie/cache.py", line 35, in __getitem__
    key_id = self._key_id(device)
  File "/usr/lib/python3.8/site-packages/udiskie/cache.py", line 24, in _key_id
    raise KeyError("Key not cached!")
KeyError: 'Key not cached!'
# third try, works
$ udiskie -T -v -c ${DOTFILES_PRIVATE}/udiskie/config.yml
```

From there, if I umount and re-run udiskie it works, unless I unplugged my harddrive, then I have to do it again.

**Comment by coldfix** [comment]
Hi,

thanks for reporting! I hope to check sometime during the next week what's wrong.

Best, Thomas

**Comment by coldfix** [comment]
some preliminary remarks:

The error you observe is just a debug message, and is not a problem, in fact you should not see it without `-v` (yes, it should be shortened not to show an error/traceback, that I will change).

Since you run udiskie with `-v` there should be a lot more output usually, some of that may be relevant, can you post it as well? In particular, I am interested, if the first run actually unlocks the partition but then just doesn't continue to mount it. Then on the following runs mounts it.

**Comment by sheoak** [comment]
@coldfix thanks, I have updated to 2.0.2 and the problem is fixed!
