### ISSUE TITLE
After power off card reader, can not turn it back on

### ISSUE THREAD

**Issue by hohol92** [coldfix/udiskie#219]
When I insert the usb stick and unplug it with Poweroff it gets unmounted, but then I plug it back in and it mounts again.
But when I plug in the microsd in card reader drive and try it with Poweroff, I can't put the flash drive back in again, dmesg doesn't show anything.
I did not find a command that turns on the turned off device, what to do?

**Comment by coldfix** [comment]
Hey,

I don't know if there is an easy way to turn it back on. You can try to find the device path under `/sys/devices/pci....` by using e.g. `udevadm info /dev/mmcblk0` (using the block device path for your card reader) and then check its power-control methods. Other ways of finding the device path include watching `udevadm monitor`  while inserting/removing the card, or as described [here](https://unix.stackexchange.com/a/125272/26773).

I can't directly compare on my laptop, because here the card reader isn't reported as removable by the system, so I can't power-off using udiskie and instead I have unpowered manually by typing:

```
echo 1 > /sys/devices/pci0000:00/0000:00:1c.0/0000:02:00.0/remove
```

[This question on SE](https://unix.stackexchange.com/questions/73908/how-to-reset-cycle-power-to-a-pcie-device) may also help. In particular, on my laptop the following command turns the device back on:

```
echo 1 > /sys/bus/pci/rescan
```

**Comment by hohol92** [comment]
I disabled with this command:
```
echo 1 > /sys/devices/pci0000\:00/0000\:00\:15.0/remove
```
After that, usb stopped working. But after this `echo 1 > /sys/bus/pci/rescan` all good
This is a problem due to the fact that there is a deep structure and it does not disable pci15, but what is mounted inside as usb1. But the problem is solved
