### ISSUE TITLE
ValueError: Namespace Gio not available on startup

### ISSUE THREAD

**Issue by LaRevoltage** [coldfix/udiskie#282]
I am on latest Arch Linux system, and after trying to start the udiskie 2.5.2-1 installed from AUR, I get the following error:
```
➜ udiskie               
Traceback (most recent call last):
  File "/usr/bin/udiskie", line 4, in <module>
    from udiskie.cli import Daemon
  File "/usr/lib/python3.11/site-packages/udiskie/cli.py", line 9, in <module>
    from .depend import has_Notify, has_Gtk, _in_X, _in_Wayland, has_AppIndicator3
  File "/usr/lib/python3.11/site-packages/udiskie/depend.py", line 13, in <module>
    require_version('Gio', '2.0')
  File "/usr/lib/python3.11/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gio not available
```

**Comment by coldfix** [comment]
Hi,
do you have `glib2` installed?
I don't see udiskie package in AUR? Did you mean the one in `extra`?

Best, Thomas

**Comment by coldfix** [comment]
This sounds weird for multiple reasons:

- there is no `udiskie` package in AUR
- the `Gio-2.0.gir` typelib belongs to `gobject-introspection` which is (indirectly) depended upon by `python-gobject` via `(via `gobject-introspection-runtime`. You seem to have `python-gobject`, since the `require_version` function that raises the error belongs to that package.
- the executed python modules are in `/usr/lib`, so it's not due to running in a virtualenv either

I suspect something is/was messed up with your installation of `python-gobject` or `gobject-introspection`. I'll close this for now as you didn't provide more information. If the problem persists, let me know, and I can reopen/investigate.
