### ISSUE TITLE
not automounting anymore?!

### ISSUE THREAD

**Issue by m0nk33** [coldfix/udiskie#42]
It seems as if udiskie v1.0.2 is not automounting anymore. 
Using arch with latest stuff. 
However I can mount with: "udiskie-mount -a"

**Comment by ernie-cordell** [comment]
My devices aren't getting automounted anymore:  I'd suspect that I'm making a stupid mistake, but I haven't intentionally made any intentional changes (not that this excuses me).  Here is the diagnostic help that occurs to me:

[udiskie-prob.txt](https://github.com/coldfix/udiskie/files/2723810/udiskie-prob.txt)

**Comment by coldfix** [comment]
Hey, your exception shows that you're using python 3.4 with a udiskie version that requires 3.5+. I did not post an official release with this backward breakage so far, so I assume you either installed it manually from github or you should notify your package maintainer about the package being broken.
