### ISSUE TITLE
udiskie -t/-T don't works on ubuntu 14.04

### ISSUE THREAD

**Issue by fenrrir** [coldfix/udiskie#59]
Hi,

  I'm trying using udskie in ubuntu 14.04 but no icon shows up on systray. I followed the installation guide here https://github.com/coldfix/udiskie/wiki/Ubuntu-Debian-installation-guide

**Comment by coldfix** [comment]
Hey,

don't know if you are still interested but I finally decided to implement this feature. However, it has to be requested explicitly. In order to use appindicators, you have to start udiskie as

```
udiskie -t --appindicators
```

Since I won't be actively checking udiskie on ubuntu it is likely that this may break at some point. In case there are any problems, error reports are always welcome. 

Thomas
