### ISSUE TITLE
udiskie not working properly with uefi partioned disks

### ISSUE THREAD

**Issue by feyyazesat** [coldfix/udiskie#61]
There is a uefi partition on my usb disk /dev/sdb and There is also partition on /dev/sdb1 and files inside.

So udiskie mounting /dev/sdb but its not mounting /dev/sdb1 and gives following errors : 

mounted /org/freedesktop/UDisks/devices/sdb on /media/Ubuntu 14.04 LTS amd64
failed to mount /org/freedesktop/UDisks/devices/sdb1: GDBus.Error:org.freedesktop.UDisks.Error.Failed: Error mounting: mount exited with exit code 1: helper failed with:
mount: /dev/sdb1 is already mounted or /media/usb0 busy

 operation failed for device: /org/freedesktop/UDisks/devices/sdb1

**Comment by coldfix** [comment]
Hey, thanks for the report. I hope I can take a closer look the next few days. Sorry, having much too do at the moment.

**Comment by coldfix** [comment]
Hey,

sorry for the long delay.

I assume, you are using a simple copy of the ubuntu image onto the usb drive.

**In that case:** You are probably using the UDisks1 backend which was still the default in the last version of udiskie (but that is already changed in master). UDisks1 is sometimes a little quirky. Can you check, whether the problem disappears by using UDisks2? Just start udiskie with `udiskie -2`. If that is an option for you and if it solves your problem, I'm not gonna invest much time in this, because there will be major changes in the control flow soon anyway.

**Otherwise:** What do you mean by *UEFI partitioned disk*? Is your disk formatted with GPT or MBR? Is there an EFI system partition? What is its name, sdb2?

Best regards,
Thomas

**Comment by coldfix** [comment]
@feyyazesat Since you haven't answered, I'm closing this issue - assuming your problem is fixed by using `udiskie -2`. Please reopen if that's not the case.
