### ISSUE TITLE
udiskie runtime dependencies

### ISSUE THREAD

**Issue by LocutusOfBorg** [coldfix/udiskie#69]
Hi again, I recently spotted (with a Debian bug report) some missing runtime dependencies to the package.

```
Package: python-udiskie
Architecture: all
Depends: gettext,
         gobject-introspection,
         python-gi | python-gi-cairo,
         python-notify,
         python-pkg-resources,
         udisks2,
         ${misc:Depends},
         ${python:Depends}


Package: python3-udiskie
Architecture: all
Depends: gettext,
         gobject-introspection,
         python-notify,
         python3-gi | python3-gi-cairo,
         python3-pkg-resources,
         udisks2,
         ${misc:Depends},
         ${python3:Depends}
```

some of them (the python*:Depends) includes PyYAML and docopt, because they are listed in install_requires setup field.

I would like to know if they are really needed the above dependencies, and know if they can be added to the setup.py (at least maybe the gi, pkg-resources and the notify packages?)

thanks

**Comment by coldfix** [comment]
Hey,
sorry, I'm not aware of any reasonable way to resolve the other dependencies via the setup.py script. Basically, in `setup.py` I can only list dependencies that can be installed via pip (from PyPI).

This excludes everything but docopt/pyyaml. pkg_resources and pygobject are special cases:
- pkg_resources is included in setuptools, which is on PyPI, but it doesn't make sense to add it to install_requires, since it must be installed before the packages in install_requires are even considered
- pygobject is on pypi but can't be installed via pip

I'm not sure that your list of dependencies is correct (I'm using archlinux, where there are different packages). Please refer to the [README](https://github.com/coldfix/udiskie#installation) and what somebody wrote on the [wiki](https://github.com/coldfix/udiskie/wiki/Ubuntu-Debian-installation-guide).

Let me know if that helps.

**Comment by LocutusOfBorg** [comment]
Hi @coldfix 

>pkg_resources is included in setuptools, which is on PyPI, but it doesn't make sense to add it to install_requires, since it must be installed before the packages in install_requires are even considered

it is installed at *build* time, not at *runtime* :)
cat /usr/bin/udiskie
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'udiskie==1.2.0','console_scripts','udiskie'
__requires__ = 'udiskie==1.2.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('udiskie==1.2.0', 'console_scripts', 'udiskie')()
    )
```

anyway, it is completely fine to add the dependencies manually in the control file, just sometimes I can forget one and get a bug :)
so if it is ok for you it is also for me, thanks!

**Comment by coldfix** [comment]
> it is installed at build time, not at runtime :)

Exactly, sorry^^

I should add, that you will probably want to resolve docopt/pyyaml via the package manager too rather rather than relying on setup.py - or is that what `${python:Depends}` does? To be honest, I tried to create a debian package for something else and I found it to be pretty hard to do (maybe you can help me).

**Comment by LocutusOfBorg** [comment]
python:Depends (I guess) looks at 
```
    install_requires=[
        'PyYAML',
        'docopt',
        # Currently not building out of the box:
        # 'PyGObject',
    ],
```

and translates this to the correct python2 and python3 Debian dependencies :)

following the runtime dependencies you can see by opening the .deb files
```
Depends: gettext, gobject-introspection, python-gi | python-gi-cairo, python-notify, python-pkg-resources, udisks2, python, python-docopt, python-yaml, python:any (<< 2.8), python:any (>= 2.7.5-5~)
```
```
Depends: gettext, gobject-introspection, python-notify, python3-gi | python3-gi-cairo, python3-pkg-resources, udisks2, python3, python3-docopt, python3-yaml, python3:any (>= 3.3.2-2~)
```
as you can see docopt and yaml magically appeared there.

If you have questions about the Debian packaging feel free to ask, it is *really* trivial (at least for python stuff)
you can see it there
http://anonscm.debian.org/cgit/collab-maint/python-udiskie.git
(look to the Debian directory)
