### ISSUE TITLE
Starting and stopping udiskie in daemon mode

### ISSUE THREAD

**Issue by fmitha** [coldfix/udiskie#93]
It seems that to start `udiskie` in daemon mode, you just need to use the command

     udiskie &

But this isn't completely clear from the documentation.
However, there doesn't seem to be a way to stop the daemon other than manually killing it.

The standardized start/stop interface, i.e.

     /etc/init.d/udiskie start | stop

might make sense. Additionally, it's possible to start multiple versions of `udiskie`,
though it doesn't make sense to do so.

                                                                                           Regards, Faheem Mitha

**Comment by coldfix** [comment]
Hey,

I believe starting udiskie as a true system daemon doesn't make a lot of sense: it's a userspace client program, much like nm-applet/kalu/volume-control/tomboy/..., which are typically started in your `.xinitrc` or using the autostart applications feature of your DE - and killed using `pkill`. You're right, I should point this out more clearly in the documentation (will get to it this week hopefully).

> Additionally, it's possible to start multiple versions of udiskie, though it doesn't make sense to do so.

Yeah. That's something that I didn't bother to prevent. You wouldn't usually try starting two udiskie instances. If you do, just kill one of them again. There shouldn't be much harm from having two udiskie instances around, except for you getting annoyed by two sets of notifications messages. IMO, I don't really think the convenience justifies the extra complexity. (Btw, you can also have two nm-applet or kalu instances).

**Comment by coldfix** [comment]
I should add that you can also exit the application by selecting `Quit` from the tray menu - unless you use the smart tray, where this doesn't really make sense.

**Comment by fmitha** [comment]
Hi Thomas,

I'm no expert on these matters, but (I think) `/etc/init.d/` files are ultimately just a convenience.

I'm not sure what you mean by "true system daemon". Mostly these run in user mode, though
the user might be a special system user.

I think it makes sense to present a standardized interface. For example if someone wants to run
udiskie at startup, it can just be dropped into the init system startup.

Regards, Faheem Mitha

**Comment by coldfix** [comment]
Hey!,

I'm no expert here either, so maybe I did (and will) make some remarks based on miss-judgements;)

It's just that
- I don't really want to bother with sysvinit style initialization
- I did make a systemd unit file for udiskie once, which was not too hard, but I've come to the conclusion nevertheless that this is more trouble than worth (e.g. you have to use a different set of permissions)
- Most users (I guess?) will want to start udiskie from inside their X session anyway and for that there is autostart applications which can be conveniently managed in most DEs or `.xinitrc` if using a stand-alone window manager
- IMO, udiskie is just a user application like your browser, file manager, nm-applet - or whatever - and as such it's more straight forward to just start/kill as any other application rather than the typical system configuration tools such as systemctl or whatever you use for sysvinit scripts
- if you really want a sysvinit-script/systemd-unit nobody hinders you from making one on your own. I'd even be willing to add it to the repository, but I will put a notice next to it saying that I'm not actively maintaining it, so you will have to update it on your own if it ever breaks;)

Sorry:(

Best regards,
Thomas

**Comment by fmitha** [comment]
Ok, Thomas. No problem. It was just a suggestion. 

I don't know if I will come up with a init script or not,
but if I do, I'll open an issue and/or a pull request for it.
Should this issue be closed?

Regards, Faheem Mitha

**Comment by mb720** [comment]
For anyone interested in starting udiskie automatically on login using systemd:

  1. Create a file `~/.config/systemd/user/udiskie.service` with this content:

            [Unit]
            Description=udiskie mounts drives when plugged in

            [Service]
            ExecStart=/usr/bin/udiskie --no-notify

            [Install]
            WantedBy=default.target

  2. Make the service execute on each login: `systemctl --user daemon-reload && systemctl --user enable udiskie`
  3. Reboot and check if udiskie was started with `pgrep udiskie`
